openapi: 3.0.3
info:
  title: Device Management API
  version: 1.0.0

paths:
  /devices:
    post:
      summary: Creates a device
      operationId: createDevice
      requestBody:
        description: A device creation request.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Device"
      responses:
        '201':
          $ref: "#/components/responses/DeviceResponse"
  /devices/{deviceId}:
    get:
      summary: Returns a device by id
      operationId: getDevice
      parameters:
        - in: path
          name: deviceId
          schema:
            type: string
          required: true
      responses:
        '200':
          $ref: "#/components/responses/DeviceResponse"

components:
  schemas:
    Device:
      type: object
      required:
        - serialNumber
      properties:
        id:
          type: string
          format: uuid
          description: The device ID.
        serialNumber:
          type: string
          description: The device serial number.
        lifeCycleState:
          type: string
          enum:
            - PENDING_INSTALL
          description: The device life-cycle state.
  responses:
    DeviceResponse:
      description: A device response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Device"
