spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:device-management
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  jackson:
    default-property-inclusion: non_null
server:
  error:
    include-message: always
